version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-template"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xngv90lhexu1"
s3_prefix = "sam-app-template"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
